### ISSUE TITLE
Remove username and password

### ISSUE THREAD

**Issue by anjmao** [trustpilot/node-trustpilot#46]
As we already have api keys management in B2B site I think we should to remove username and password fields from api.

```
let client = new Trustpilot(
  {
    apiKey: 'YOUR-API-KEY',
    secret: 'YOUR-SECRET',
    username: 'YOUR-TRUSTPILOT-B2B-USERNAME', // <-remove this
    password: 'YOUR-TRUSTPILOT-B2B-PASSWORD' // <-remove this
  });
```

Note: this is breaking change and release number should be updated accordingly to follow semver.

**Comment by b-dur** [comment]
This package is not only used for our b2b site. Other users outside of TP are also using this module, and username and password are needed in cases, when they want to access the private endpoints.

However, I would like to see the AccessProvider was more modular, so it was possible to change to a different provider. Say a b2b AccessProvider which could accept an apiKey and an accessToken, and that provider could also handle refreshToken communication if needed.
Another example could be, another simpler AccessProvider, that only allowed accessing public API endpoints.

**Comment by martinbuberl** [comment]
@anjmao Does Bardur's answer it? Can I close the issue?

**Comment by b-dur** [comment]
@martinbuberl guess we can close this issue.
