### ISSUE TITLE
Reply not added to trustpilot

### ISSUE THREAD

**Issue by prsaravana0712** [trustpilot/node-trustpilot#57]
I am trying to add a reply to the Trustpilot review by using Trustpilot npm package.
But I got this error.

statusCode: 400,
message: '400 - {
	"message":"The request was malformed",
	"errorCode":1001,
	"details":"",
	"correlationId":"2e03bbf2-2978-442e-9302-3c875b696f79"
}',

**Comment by b-dur** [comment]
Hi @prsaravana0712, 
how does your post call look like?
It should be something similiar:
`const options = {
  url: 'https://api.trustpilot.com/v1/private/reviews/${reviewId}/reply',
  method: 'POST',
  body: {
    message: 'your reply'
  },
  json: true
}
client(options)`
